/**
 * Teleport
 * Copyright (C) 2026  Gravitational, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/gravitational/teleport/e2e/runner/fixtures"
)

var tmpl = template.Must(template.New("fixtures.ts").Parse(`/**
 * Teleport
 * Copyright (C) 2026  Gravitational, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// Code generated by e2e/runner/cmd/gen-ts-fixtures; DO NOT EDIT.

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { test as base } from '@playwright/test';

type Fixture =
{{- range .Fixtures}}
  | '{{.Name}}'
{{- end}};

type UserRole = string | { file: string };

interface UserTraits {
  logins?: string[];
  windows_logins?: string[];
  kubernetes_groups?: string[];
  kubernetes_users?: string[];
  db_names?: string[];
  db_users?: string[];
  db_roles?: string[];
  aws_role_arns?: string[];
  azure_identities?: string[];
  gcp_service_accounts?: string[];
  host_user_uid?: string[];
  host_user_gid?: string[];
  [key: string]: string[] | undefined;
}

interface UserDefinition {
  roles: UserRole[];
  traits?: UserTraits;
  recordings?: string[];
  loginAs?: boolean;
}

const authDir = join(
  dirname(fileURLToPath(import.meta.url)),
  '../.auth'
);

/**
 * Computes a canonical key for a UserDefinition that matches the key
 * produced by the Go runner. Used to look up generated usernames from
 * the user-mapping.json file.
 */
function canonicalUserKey(def: UserDefinition): string {
  const roles = def.roles
    .map(r => (typeof r === 'string' ? r : ` + "`@file:${r.file.replace('@gravitational/e2e/roles/', '')}`" + `))
    .sort();

  const result: { roles: string[]; traits?: Record<string, string[]> } = { roles };

  if (def.traits) {
    const sorted: Record<string, string[]> = {};
    for (const k of Object.keys(def.traits).sort()) {
      const v = def.traits[k];
      if (v) {
        sorted[k] = [...v].sort();
      }
    }

    if (Object.keys(sorted).length > 0) {
      result.traits = sorted;
    }
  }

  return JSON.stringify(result);
}

function resolveActiveUser(
  user: UserDefinition | undefined,
  users: UserDefinition[]
): string {
  const mappingPath = join(authDir, 'user-mapping.json');

  let mapping: Record<string, string>;
  try {
    mapping = JSON.parse(readFileSync(mappingPath, 'utf-8'));
  } catch {
    return '';
  }

  let loginDef: UserDefinition | undefined;
  if (user) {
    loginDef = user;
  } else if (users.length > 0) {
    loginDef = users.find(u => u.loginAs) ?? users[0];
  }

  if (!loginDef) {
    return '';
  }

  return mapping[canonicalUserKey(loginDef)] ?? '';
}

interface E2EFixtures {
  fixtures: Fixture[];
  recordings: string[];
  user: UserDefinition;
  users: UserDefinition[];
  username: string;
}

export const test = base.extend<E2EFixtures>({
  fixtures: [[], { option: true }],
  recordings: [[], { option: true }],
  user: [undefined as unknown as UserDefinition, { option: true }],
  users: [[], { option: true }],
  username: async ({ user, users }, use) => {
    await use(resolveActiveUser(user, users));
  },
  storageState: async ({ username }, use, testInfo) => {
    if (!username) {
      await use(undefined as unknown as string);
      return;
    }

    const browser = testInfo.project.name.split(':')[0];

    await use(join(authDir, ` + "`${browser}-${username}.json`" + `));
  },
});
`))

func main() {
	all := fixtures.All()
	if len(all) == 0 {
		fmt.Fprintln(os.Stderr, "no fixtures registered")
		os.Exit(1)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, struct{ Fixtures []*fixtures.Fixture }{all}); err != nil {
		fmt.Fprintf(os.Stderr, "executing template: %v\n", err)
		os.Exit(1)
	}

	outPath := filepath.Join("..", "helpers", "fixtures.ts")
	if err := os.WriteFile(outPath, buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "writing %s: %v\n", outPath, err)
		os.Exit(1)
	}

	fmt.Printf("generated %s with %d fixture(s)\n", outPath, len(all))
}
